name: Deploy to EC2

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.TESTKEYPAIR }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.TESTKEYPAIR }} ec2-user@ec2-13-233-131-118.ap-south-1.compute.amazonaws.com 'bash -s' < deploy-script.sh
